---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig-map
data:
  qt: bhavana


---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  aws: a2hhamE=

---
apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  labels:
    app: test
spec:
  containers:
    - name: my-container
      image: nginx:1.25
      ports: 
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
      volumeMounts:
        - name: myvoluone
          mountPath: /var/lib/username
        - name: mysectreone
          mountPath: /var/lib/password   
  volumes:
    - name: myvoluone
      configMap:
        name: myconfig-map

    - name: mysectreone
      secret:
        secretName: my-secret


  

