---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-rs
  name: repicca  
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nignix
  template:
    metadata:
      labels:
        app: nignix
    spec:
      containers:
        - image: nginx:1.25
          name: ngix-pod
          ports:
            - containerPort: 80
              protocol: TCP

          
    
  

