---
apiVersion: v1
kind: Service
metadata:
  name: myclusreipservice
  labels:
    nothing: something
spec:
  selector:
    apps: nignixss
  type: ClusterIP
  ports: 
    - port: 80
      targetPort: 80