---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: nignix
spec:
  containers:
    - name: mycontainer
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP



