---
apiVersion: v1
kind: Service
metadata:
  name: auditlogservice-service
spec:
  selector:
    app: auditlog
  ports:
    - name: http
      port: 80  
      
---
apiVersion: v1
kind: Service
metadata:
  name: pitstopservice
  labels:
    env: dev
spec:
  selector:
    app: rabbitmq
  ports:
    - name: managment
      targetPort: 15672
      port: 15672
    - name: message
      targetPort: 5672
      port: 80
