---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: nginx12
    env: test
spec:
  initContainers:
    - name: my-init
      image: alpine
      command:
        - sleep
        - 15s
  containers:
    - name: my-container
      resources:
        requests:
          memory: "700mi"
          cpu: "250m"
        limits:
          memory: "850mi"
          cpu: "500m"
      image: nginx:1.25
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP

            

            
          
            
      
          
               
      
      
      
